server:
  port: 8080  # API Gateway'in iç portu

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: tariff-service
          uri: lb://tariff-service  # Load balancer ile mikroservise erişim
          predicates:
            - Path=/api/tariffs/**
        - id: package-creator-service
          uri: lb://package-creator-service
          predicates:
            - Path=/api/parking-packages/**
        - id: customer-type-service
          uri: lb://customer-type-service
          predicates:
            - Path=/api/customer-types/**
        - id: vehicle-type-service
          uri: lb://vehicle-type-service
          predicates:
            - Path=/api/vehicle-types/**
        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/api/districts/**
  discovery:
    locator:
      enabled: true  # Servis keşfi etkinleştirildi

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
